# Generated by Django 3.2 on 2022-02-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='lineItem_total',
            new_name='lineitem_total',
        ),
    ]
