# Generated by Django 3.2 on 2022-02-19 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='friendly_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
